import dots from "../../../../public/assets/Images/3dots.svg";
import Failed from "../../../../public/assets/Images/failed.svg";
import Success from "../../../../public/assets/Images/success.svg";

export const transactionHistory = [
  {
    src: dots,
    coinName: "Bitcoin",
    coinDescription: "From Badgley",
    valueBTC: "+0.0010 BTC",
    value: "+$900",
    date: "2023-07-30",
    type: "purchase",
  },
  {
    coinDescription: "From Leslie Alexander",
    valueBTC: "+0.0030 BTC",
    value: "+$1,200",
    date: "2023-06-30",
    type: "purchase",
    src: Success,
    coinName: "Bitcoin",
  },
  {
    value: "+$976",
    date: "2023-06-28",
    type: "purchase",
    src: Failed,
    coinName: "Bitcoin",
    coinDescription: "From Bitcoin1",
    valueBTC: "+0.0240 BTC",
  },
  {
    type: "purchase",
    src: Success,
    coinName: "Bitcoin",
    coinDescription: "From Bicoin0",
    valueBTC: "+0.0230 BTC",
    value: "+$786",
    date: "2023-06-26",
  },
  {
    coinName: "Cardano",
    coinDescription: "From Bitcoin5",
    valueBTC: "+0.0270 BTC",
    value: "+$9869",
    date: "2023-06-24",
    src: Failed,
    type: "purchase",
  },
  {
    valueBTC: "+0.02760 BTC",
    value: "+$8768",
    date: "2023-06-05",
    type: "purchase",
    src: Failed,
    coinName: "Cardano",
    coinDescription: "From Bitcoin2",
  },
  {
    valueBTC: "+0.0860 BTC",
    value: "+$8756",
    src: dots,
    coinName: "Cardano",
    coinDescription: "From Badgley",
    date: "2022-07-25",
    type: "purchase",
  },
  {
    coinName: "Cardano",
    coinDescription: "From Cardano5",
    valueBTC: "+0.7650 BTC",
    value: "+$8768",
    date: "2022-07-18",
    type: "purchase",
    src: Failed,
  },
  {
    src: dots,
    coinName: "Tether",
    valueBTC: "+0.0776 BTC",
    value: "+$8757",
    date: "2023-06-16",
    type: "purchase",
    coinDescription: "From Cardano8",
  },
  {
    src: Success,
    coinName: "Tether",
    coinDescription: "From Tether3",
    valueBTC: "+0.876 TEH",
    value: "+$8746",
    date: "2023-03-14",
    type: "sell",
  },
  {
    src: Failed,
    coinName: "Ethereum",
    coinDescription: "From Ethereum2",
    valueBTC: "+0.65BTC",
    type: "purchase",
    value: "+$7653",
    date: "2023-05-27",
  },
  {
    src: dots,
    date: "2022-11-19",
    type: "purchase",
    coinName: "Ethereum",
    coinDescription: "From Issac",
    valueBTC: "+0.8768 ETH",
    value: "+$1340",
  },
  {
    src: Failed,
    coinName: "Ethereum",
    coinDescription: "From Newton",
    value: "+$1567",
    date: "2022-10-11",
    type: "purchase",
    valueBTC: "+0.6798 ETH",
  },
];
